[package]
name = "persona-exporter-types"
version = "2.2.1"
edition = "2024"
description = "Data types for persona-exporter"
repository = "https://github.com/0DoubleDare/persona-exporter-types"
license = "MIT OR Apache-2.0"

[dependencies]
cfg-if = "1.0.4"

serde = { version = "1.0.228", features = ["derive"], optional = true }
influxdb-line-protocol = { version = "2.0.0" , optional = true }
sysinfo = { version = "0.39.6", optional = true }

smallvec = { version = "1.16.1", default-features = false,  features = ["serde", "union"] }
compact_str = { version = "0.10.0", default-features = false, features = ["serde"] }

[features]
default = ["serde", "convert-data-unit"]
serde = ["dep:serde"]
line-protocol = ["dep:influxdb-line-protocol"]
from-trait-sysinfo = ["dep:sysinfo"]
convert-data-unit = []

disk = []
system = []
memory = []
components = []
cpu = []
processes = []
network = []

full = [
    "serde",
    "line-protocol",
    "convert-data-unit",
    "from-trait-sysinfo",
    "disk",
    "system",
    "memory",
    "components",
    "cpu",
    "processes",
    "network",
]
