name: Release on crates.io

on:
  workflow_call:

permissions:
  contents: write

jobs:
  publish:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    environment: publish-and-release-crate
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
        with:
          shared-key: "co-cache-${{ hashFiles('**/Cargo.lock**') }}"

      - name: Release on crates.io
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish

      - name: Release on Github Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.ref_name }}
          name: Release v${{ github.ref_name }}
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
